# Generated by Django 4.0.5 on 2022-07-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
